### ISSUE TITLE
Error with the Upgraded Netherite Spartan mod and the Spartan Weaponry Mod

### ISSUE THREAD

**Issue by SylTheGuy** [ObliviousSpartan/SpartanWeaponry-API#18]
![Minecraft_ 1 16 5 1_15_2024 3_27_10 PM](https://github.com/ObliviousSpartan/SpartanWeaponry/assets/156718691/665087ee-aad8-4429-b436-bcafb11f0f25)

**Comment by ObliviousSpartan** [comment]
This has to do with a unwise decision to make the release version of Spartan Weaponry 2.2.0 after 2.2.0 rc 2. It confused the versioning of the addon mod. Sorry about that. I'll look into testing to see if pushing the version to 2.2.1 will fix this

**Comment by ObliviousSpartan** [comment]
Unfortunately there wasn't anything I could do about this on my end, as the addon mod is strictly enforcing the version it is compatible with as 2.2.0 release candidate 2, rather than being forward compatible.
The issue is already closed but I thought I better give an explanation.
