### ISSUE TITLE
Bows always need a Callback implementation

### ISSUE THREAD

**Issue by Kovak** [ObliviousSpartan/SpartanWeaponry-API#2]
It seems like there should be a createLongbow and friends that doesn't take a callback when you just want the default behavior with a new material.

**Comment by ObliviousSpartan** [comment]
You can just pass this argument as null and it should be OK.

**Comment by Kovak** [comment]
good to know

**Comment by Meylin-Messor** [comment]
I did not mean to mention this post, it was an accident.
