### ISSUE TITLE
Throwing Weapons don't have charge-up damage in 1.16.5

### ISSUE THREAD

**Issue by TsEndere** [ObliviousSpartan/SpartanWeaponry-API#23]
I will provide additional information if needed.

The post is saying throwing weapons don't have less damage if you don't charge them up fully. I believe this is a thing in 1.12 but not in 1.16.

**Comment by ObliviousSpartan** [comment]
Oh yeah! I forgot that I added that specifically for RLCraft! I should probably add that in the newer versions too, including 1.16.5, 1.18.2 and 1.19.2

**Comment by ObliviousSpartan** [comment]
I've updated three versions of the mod (1.16.5, 1.18.2 and 1.19.2) to add this feature in them.
Closing issue.
