### ISSUE TITLE
Spanish translation 1.19

### ISSUE THREAD

**Issue by alexvirgo13** [ObliviousSpartan/SpartanWeaponry-API#25]
I finished off a spanish translation since the one the mod had seemed incomplete, hopefully it's useful
[es_es.json](https://github.com/ObliviousSpartan/SpartanWeaponry/files/14321489/es_es.json

**Comment by ObliviousSpartan** [comment]
Thanks a bunch for this! I'll add this to the next update as well.

**Comment by ObliviousSpartan** [comment]
I've added the translation in the 1.18.2 and 1.19.2 versions of the mod. Thanks again.
Closing issue.
