### ISSUE TITLE
[1.18.2] Footwork Incompatibility 

### ISSUE THREAD

**Issue by 3247332139** [ObliviousSpartan/SpartanWeaponry-API#27]
My game crashed when I tried to start it

Reproduce environment:
Forge 1.18.2-40.2.17
SpartanWeaponry-1.18.2-3.0.4
footwork-2.0
cloakanddagger-1.0
embeddium-0.3.5+mc1.18.2
footwork-2.0
embeddiumplus-1.18.2-v1.2.4
SpartanShields-1.18.2-3.0.1
starlight-1.0.2+forge
textrues_embeddium_options-0.1.1+mc1.18.2
oculus-mc1.18.2-1.6.4

[debug.log](https://github.com/ObliviousSpartan/SpartanWeaponry/files/14545877/debug.log)
[latest.log](https://github.com/ObliviousSpartan/SpartanWeaponry/files/14545878/latest.log)

**Comment by ObliviousSpartan** [comment]
This is a known issue.
I've had contact with someone who knows the developer of Footwork that told me about this. This also affects the 1.19.2 version of the mod too.
I'm looking into making a fix for this

**Comment by ObliviousSpartan** [comment]
I've just released a fix for the redirect conflict that was causing the Footwork API to crash. I was hoping to add integration to Cloak and Dagger and Project War Dance, but that will have to wait. I hope to do this when I release this mod for 1.20.1.
Closing this issue as it's resolved.
