### ISSUE TITLE
Sugestion: Two-Handed should work in offhand

### ISSUE THREAD

**Issue by alexvirgo13** [ObliviousSpartan/SpartanWeaponry-API#30]
I think i'd be cool if the two handed trait detected if a two handed weapon is in the offhand in case there's a dual/offhand(?) wield mod installed. It probably isn't too hard to implement

**Comment by ObliviousSpartan** [comment]
I thought that I had set up two handed weapons to give their attack damage and speed penalties when they are in their off-hand already! This functionality might have fallen through the cracks while I was updating the mod for the newer versions of Minecraft. I'll take a look into this.

**Comment by ObliviousSpartan** [comment]
I've implemented this in the upcoming 1.18.2 and 1.19.2 updates. I still don't know why it was overlooked though

**Comment by ObliviousSpartan** [comment]
The fix for this issue is now live.
Closing issue as it's resolved.
