### ISSUE TITLE
Suggestion: Option to turn off Mining Fatigue || change weapon traits

### ISSUE THREAD

**Issue by Xarmat-GitHub** [ObliviousSpartan/SpartanWeaponry-API#32]
### **Description:** 
Give pack makers the option to turn off negative status effects for weapons with the "Two-Handed" trait. In this case, "mining fatigue". _**Requested Version;** 1.12.2 (personal wish)_

### **Lore:** 
I have the need of giving players the freedom to swing a two handed weapon while holding an item in the off hand: e.g. Lantern + Dynamic Light, Bombs, more consumables, etc.

### **More Ideas _spam_:**
- create a config to setup a white- / blacklist for off hand items (e.g. Shields)
- expand config to allow setting traits for each weapon type separately (e.g. replace all Rapier traits and give new trait "chest damage bonus") - makes it more configurable for personal use and mod pack creators

_So far, thanks for this amazing mod and your efforts._ 🙌

**Comment by Xarmat-GitHub** [comment]
Optional: Give the config an option to turn off all traits in the mods (all / only negative).

**Comment by Joakoppp** [comment]
I think it is unnecessary but everyone wants what they want

**Comment by Xarmat-GitHub** [comment]
> I think it is unnecessary but everyone wants what they want

Its the question what the Author of the mod vision is on his project.
I personally see the power in control for the mod-pack community.
I found a workaround for my issue by cancelling the potion effect. Not the best solution, but works for me.

_Workaround: Use "SetEffect" mod and make player immune to potion effects of your choice._
