### ISSUE TITLE
Constantan and Aluminum weapons still in JEI despite disabling in config

### ISSUE THREAD

**Issue by Chokedamp** [ObliviousSpartan/SpartanWeaponry-API#34]
Minecraft 1.19.2, Forge 43.3.0, SpartanWeaponry-1.19.2-3.0.5-all.jar, jei-1.19.2-forge-11.6.0.1019.jar

I disabled all non-vanilla materials, but Constantan and Aluminum weapons still appear in Just Enough Items:
![Spartan01](https://github.com/ObliviousSpartan/SpartanWeaponry/assets/123910214/438621c1-0eaf-413a-ab96-5bba2ca1cfab)
![Spartan02](https://github.com/ObliviousSpartan/SpartanWeaponry/assets/123910214/516fd168-ab5d-4f8f-90ca-7cc35571f154)
![Spartan03](https://github.com/ObliviousSpartan/SpartanWeaponry/assets/123910214/4a9e17c7-1b6e-4654-abd8-c20898892d57)
![Spartan04](https://github.com/ObliviousSpartan/SpartanWeaponry/assets/123910214/9fdcc774-6239-4168-93e2-62a128f93014)
![Spartan05](https://github.com/ObliviousSpartan/SpartanWeaponry/assets/123910214/f6029641-10a7-4283-af4a-c6607a462c57)
![Spartan06](https://github.com/ObliviousSpartan/SpartanWeaponry/assets/123910214/34bbedd3-81e5-4922-8cdd-80d3995d39db)
![Spartan07](https://github.com/ObliviousSpartan/SpartanWeaponry/assets/123910214/3d06278a-a6a3-4a47-afe6-676d197357ae)

**Comment by ObliviousSpartan** [comment]
Hey,
I figured out why this happened. I forgot to add the logic that remove the weapons for the new materials when disabled. This has been remedied now and will be fixed in the next update

**Comment by ObliviousSpartan** [comment]
I've uploaded a new version that allows Constantan and Aluminum to be hidden is JEI now. Finally!
Closing this issue
