### ISSUE TITLE
Compatibility issue with Leawind's Third Person

### ISSUE THREAD

**Issue by Chokedamp** [ObliviousSpartan/SpartanWeaponry-API#38]
Tested with Minecraft 1.19.2, Forge 43.3.0, [Leawind's Third Person 2.0.7](https://modrinth.com/mod/leawind-third-person/version/2.0.7) and Spartan Weaponry 3.0.5.

[Leawind's Third Person](https://modrinth.com/mod/leawind-third-person) is my preferred third person camera mod, but there seems to be an issue with Spartan Weaponry's custom crosshairs.

While in third person, the crosshair disappears entirely if the main hand is holding a Heavy Crossbow, Throwing Knife, Tomahawk, Javelin, or Boomerang. If held in the offhand, the default crosshair is displayed. Notably, this problem does not occur in either hand while holding a Dagger, Longbow, or Dynamite, which are throwable or projectile weapons that don't use custom crosshairs.

None of the settings in the client config changed the behavior of either hand. (In fact, changing `disable_new_crosshairs_crossbow` and `disable_new_crosshairs_throwing_weapons` to true seemed to remove the crosshair from _first_ person rather than replacing it with the default crosshair.)

To replicate the issue, enter third person mode and hold a Heavy Crossbow or a throwing weapon in your main hand.

**Comment by ObliviousSpartan** [comment]
Hey,
Isn't the default vanilla behavior for third-person mode is to hide the crosshair? Because if that's so, then that must mean Leawind's Third Person mod is changing that behavior and my mod has no idea that's happening.
To enable this behavior, I will need to allow the crosshair to draw on the screen when that mod is installed.
I'll see what I can do.

**Comment by Chokedamp** [comment]
That is vanilla behavior, yes. Leawind's mod draws the regular crosshair during third person mode.

I tested a couple third-person mods to have a point of comparison (vanilla, Leawind's, Better Third Person, Shoulder Surfing Reloaded) and ultimately decided to open an issue here due to the crosshair behavior for throwing weapons in the offhand as well as the behavior of the crosshair config settings.

**Comment by ObliviousSpartan** [comment]
I've uploaded a new version of the mod that lets the mod draw the crosshair when Leawinds Third Person is installed.
Closing issue.
