### ISSUE TITLE
At the request of the entire mod community.

### ISSUE THREAD

**Issue by Joakoppp** [ObliviousSpartan/SpartanWeaponry-API#39]
How close are we to 1.20.1 coming out? Or else, is an update planned for those versions?. 
I ask you this because the entire community is intrigued by it, don't take this the wrong way, we don't want to rush you or anything, it's just for the intrigue, thank you very much for everything you do for the mod, it's one of the best there is and I really appreciate your job. 
Sorry if my English is bad it's because I used Google Translate.
I await a response from you, thank you very much for everything.

**Comment by ObliviousSpartan** [comment]
I just released that version now. Enjoy.
Closing
