### ISSUE TITLE
Keybinds

### ISSUE THREAD

**Issue by nerostudios** [ObliviousSpartan/SpartanWeaponry-API#41]
Im playing a 1.19.2 modpack with friends. There is no way to change the keybind for the quiver in the options and its interfering with other mods. Is there some way to change the quiver key bind at all? I looked even in the config files and found nothing.

**Comment by ObliviousSpartan** [comment]
I've just checked the 1.19.2 version of the mod and I just realized the key for changing this in the options menu is gone!
I forgot to register the keybind in my code! Oops.
I'll push a quick update to fix this soon.

**Comment by nerostudios** [comment]
> I've just checked the 1.19.2 version of the mod and I just realized the key for changing this in the options menu is gone! I forgot to register the keybind in my code! Oops. I'll push a quick update to fix this soon.

tysm, ill look 4 the update when it comes out, would i need to update the server side as well?

**Comment by ObliviousSpartan** [comment]
I've released the fix in the newest 1.19.2 version... and just realized that I forgot to add the fix to the newly released 1.20.1 version. I'm gonna keep this issue open in the meantime until I've fixed that one too.

**Comment by ObliviousSpartan** [comment]
I've finally fixed this issue in the 1.20.1 version now.
Closing issue
