### ISSUE TITLE
Translation issues (+JEI)

### ISSUE THREAD

**Issue by SplashedTomato** [ObliviousSpartan/SpartanWeaponry-API#42]
(played on version 1.18.2) For some reason I see only separate parts of the translation for all items (I play in Russian)  + Constantan and Aluminum weapons still in JEI despite disabling in config
Update: I looked at your previous replies to other people and found the correct en_us.json file. I'm translating now.
Update2: First translation version:
[ru_ru.json](https://github.com/user-attachments/files/15886576/ru_ru.json)

![a](https://github.com/ObliviousSpartan/SpartanWeaponry/assets/172827441/b26b8efb-e604-48ef-b991-9d581b8facad)
![b](https://github.com/ObliviousSpartan/SpartanWeaponry/assets/172827441/2ca7426d-5129-486b-865e-e08434031a71)
![c](https://github.com/ObliviousSpartan/SpartanWeaponry/assets/172827441/d879bf2a-db18-44c2-92f9-a187fa0bde25)
![f](https://github.com/ObliviousSpartan/SpartanWeaponry/assets/172827441/61f2d936-0c82-4b5e-a64e-4715095b3c06)
Вкл means ON
![d](https://github.com/ObliviousSpartan/SpartanWeaponry/assets/172827441/19835586-0db0-4fd5-b61b-f3209106264d)
![e](https://github.com/ObliviousSpartan/SpartanWeaponry/assets/172827441/767c46d7-f57a-4083-b694-2bfdc96d8921)
Вкл means ON

**Comment by ObliviousSpartan** [comment]
Thanks for the report, and the translation file!
I had fixed the second part of this issue in the 1.19.2 version of the mod. I should consider fixing it in the 1.18.2 version too. 
With your permission, I would like to add your translation file to the mod. Is this okay with you?

**Comment by SplashedTomato** [comment]
Thanks for your reply! Yes, I'm fine with that.

**Comment by ObliviousSpartan** [comment]
I've added this translations to the latest 1.20.1 release (version 3.1.1). I've also added you to the credits of the mod.
Thanks a bunch for the translation.
I should probably also add it to the 1.18.2 and 1.19.2 versions too. I'll sort that out later.
