### ISSUE TITLE
1.20.1 Crash with Supplementaries Mod

### ISSUE THREAD

**Issue by SuperStefan97** [ObliviousSpartan/SpartanWeaponry-API#43]
I have been playing in this world for some time already and just added the 1.20.1 builds of Spartan Weaponry and Shields (btw, big thanks for updating it, I missed it from 1.16.5).
When adding both mods, the world crashes and reports the following:
[crash-2024-06-14_11.08.30-client.txt](https://github.com/user-attachments/files/15841381/crash-2024-06-14_11.08.30-client.txt)
It happened twice, and solved when removing the mods, so I'm sure it has to do with them. In case it's needed, here's also the latest.log.
[latest.log](https://github.com/user-attachments/files/15841389/latest.log)
I hope it can be fixed soon, and again, thanks for updating your mods, they are awesome!

**Comment by DeshiDesu** [comment]
This may only be related to spartan shields, since they use banners in their recipes. I assume you would be safe if you only use spartan weaponry with supplementaries.

**Comment by SuperStefan97** [comment]
You were right! Works fine with only Spartan Weaponry, thanks. (Tho shields still would need a fix)

**Comment by DeshiDesu** [comment]
You should move this issue to the spartan shield repo

**Comment by SuperStefan97** [comment]
I'm not sure how to properly move it, but I found another bug report about the same thing and commented with this issue link. Thanks for ur help

**Comment by PhilTheGreatLOL** [comment]
[crash-2024-06-15_15.28.25-server.txt](https://github.com/user-attachments/files/15846208/crash-2024-06-15_15.28.25-server.txt)
Same as me, I also experience this too.

**Comment by SuperStefan97** [comment]
Post it too on the Shields issue page, might be more useful there

**Comment by ObliviousSpartan** [comment]
Thanks for the reports,
I'm gonna close this issue since it isn't related to Spartan Weaponry. Keep an update on it here: https://github.com/ObliviousSpartan/SpartanShields/issues/3
