### ISSUE TITLE
supplementaries mod crash

### ISSUE THREAD

**Issue by 821lemur** [ObliviousSpartan/SpartanWeaponry-API#46]
Error while creating worlds when used with Supplementaries mod

**Comment by ObliviousSpartan** [comment]
Update Spartan Shields to the latest version.
The issue with that mod has already been fixed. This mod loads fine with Supplementaries.
Closing issue.

**Comment by 821lemur** [comment]
thanks

ObliviousSpartan ***@***.***>, 24 Haz 2024 Pzt, 19:45
tarihinde şunu yazdı:
