### ISSUE TITLE
Addons need their own translations for trait types

### ISSUE THREAD

**Issue by KreloX** [ObliviousSpartan/SpartanWeaponry-API#47]
in [WeaponTrait.initTooltipTypes](https://github.com/ObliviousSpartan/SpartanWeaponry/blob/84daf1ddfcce3253993b8dea0b3789a4b39c91c2/src/main/java/com/oblivioussp/spartanweaponry/api/trait/WeaponTrait.java#L354) the trait type component should always use Spartan Weaponry's modid, not the addon's one. 

Currently, all addons wishing to add a new trait using the api need to either have their own translations for "melee", "throwing", etc. or use a workaround.

**Comment by ObliviousSpartan** [comment]
Oh good find! My bad. I'll push a fix for this whenever I can.

**Comment by KreloX** [comment]
Also, in [ModelGenerator.createMeleeWeaponModels](https://github.com/ObliviousSpartan/SpartanWeaponry/blob/e365ed1291d4b9cd5799226278901da2e667ed5d/src/main/java/com/oblivioussp/spartanweaponry/api/data/model/ModelGenerator.java#L56) the coating textures should always use the spartanweaponry id too.
`texture("coating", coatingTexture.getPath())` should be `texture("coating", coatingTexture)`

**Comment by ObliviousSpartan** [comment]
Noted and fixed! I just need to review what else needs to be fixed and if the API changes break anything before I push the next 1.20.1 update.

**Comment by ObliviousSpartan** [comment]
The new version with these fixes is live now!
I've tested the fixes I've made with this issue and your other one with your existing addon mods and it doesn't appear to have broken anything.
Thanks for letting me know about these again.
Closing issue
