### ISSUE TITLE
Quiver with incorrect size

### ISSUE THREAD

**Issue by lid24249** [ObliviousSpartan/SpartanWeaponry-API#49]
![incorrect_quiver](https://github.com/ObliviousSpartan/SpartanWeaponry/assets/173833464/35012eda-cd32-4653-88b0-e5efe974f5ff)
When upgrading a quiver/bolt quiver using a smithing table in 1.20.1, the Ammo.Size nbt tag of the resulting quiver doesn't seem to get increased accordingly, creating a glitchy quiver with an incorrect storage size.

**Comment by ObliviousSpartan** [comment]
I've just found out that you're right about the Ammo.Size NBT not being set properly, since it just copies the value of the original Quiver.
I've fixed this by ensuring the size is updated when the upgrade recipe is applied.
This will be included in the next update.

**Comment by ObliviousSpartan** [comment]
Initially you would've had to upgrade the quiver again to fix this issue, but I've made it so all you should have to do is open the GUI to fix it.
This will also be included in the next update.

**Comment by ObliviousSpartan** [comment]
The update with this fix is now live!
Closing issue
