### ISSUE TITLE
Update for 1.17

### ISSUE THREAD

**Issue by MrMelon54** [ObliviousSpartan/SpartanWeaponry-API#5]
After a comment on reddit I was going to try updating this mod for 1.17 and leaving a PR but unfortunately its only the api so I wouldn't be updating the whole mod. As the dev for the mod can you update to 1.17. Thanks in advance

**Comment by ObliviousSpartan** [comment]
Sadly, I can't do this until Minecraft Forge updates to 1.17. 
Closing the issue until something can be done about it.

**Comment by ObliviousSpartan** [comment]
Just thought to throw an update your way that Minecraft Forge for 1.17.1 is out now, and porting my mods to that version might take a while. Throwing my 1.16.x source code for Spartan Weaponry into a 1.17.1 version gave me roughly over 4500 errors! A lot of these are to do with name changes that I'll need to deal with first before I can see what has been removed or changed.

**Comment by MrMelon54** [comment]
ah yes typical minecraft modding
