### ISSUE TITLE
netherite bold of harming

### ISSUE THREAD

**Issue by pokerfacexx** [ObliviousSpartan/SpartanWeaponry-API#50]
Hello i made netherite bold of harming and i cant shoot it with crossbow or maybe just dont know how bcs i cant put them in quiver

**Comment by ObliviousSpartan** [comment]
Thanks for letting me know!
This is related to issue #52 and applies to any Diamond or Netherite Tipped Bolt. It has been fixed in the next update.

**Comment by ObliviousSpartan** [comment]
The update with this fix is now live!
Closing issue
