### ISSUE TITLE
supplementaries mod error

### ISSUE THREAD

**Issue by 821lemur** [ObliviousSpartan/SpartanWeaponry-API#51]
Error creating worlds when used with Supplementaries mod

**Comment by FirdausCraft10** [comment]
Supplementaries work with spartan weaponry i think u missed something like mod library

**Comment by ObliviousSpartan** [comment]
> Supplementaries work with spartan weaponry i think u missed something like mod library

Yeah this was actually a problem with the initial 1.20.1 release of Spartan Shields, which was fixed not long afterwards.
Closing issue.
