### ISSUE TITLE
Issues with tipped bolts

### ISSUE THREAD

**Issue by lid24249** [ObliviousSpartan/SpartanWeaponry-API#52]
In 1.20.1, tipped bolts (of any kind) shot by a crossbow have a missing texture (tipped arrows have their proper texture though).  

Additionally, diamond and netherite tipped bolts cannot be shot from a crossbow, as they are not in the spartanweaponry:bolts item tag (manually putting them in the item tag using a datapack fixed the issue for me).

**Comment by ObliviousSpartan** [comment]
Thanks for letting me know about this!
I've added both the Diamond and Netherite Tipped Bolts in the `spartanweaponry:bolts` tag, which will be in the next 1.20.1 update

**Comment by lid24249** [comment]
Do you know what's causing the missing textures though?

**Comment by ObliviousSpartan** [comment]
Yeah, that was due to a renaming oversight. I forgot to change the name for the entity textures when I initially made version 3.0. It's been fixed now (and was already fixed in versions for MC 1.18.2 and 1.19.2)

**Comment by ObliviousSpartan** [comment]
The update with both fixes is now live!
Closing issue
