### ISSUE TITLE
Compatibility: Spartan Weaponry and Tetra Compatibility

### ISSUE THREAD

**Issue by StormbringerGTX** [ObliviousSpartan/SpartanWeaponry-API#54]
A few years ago someone suggested compatibility between Spartan Weaponry and Tetra on the Tetra github:
https://github.com/mickelus/tetra/issues/324 #

Multiple people in our server have been making requests for this compatibility, so I wanted to check if this was on your radar already?

https://www.curseforge.com/minecraft/mc-mods/tetra

**Comment by AnonTheMouse** [comment]
Bad bot. No biscuit.

**Comment by JoatMasterofNun** [comment]
Gddddmnit there was so much hope. I actually came across the other request first and saw this linkback. (;'_';)

**Comment by AnonTheMouse** [comment]
Same here. Though I think it's safe to say that there's still interest in this, so please?

**Comment by ItsYuriil** [comment]
Definetly hoping for some compatibility between mods
