### ISSUE TITLE
Configs not working 1.18.2-3.0.5-all

### ISSUE THREAD

**Issue by Adam19lol** [ObliviousSpartan/SpartanWeaponry-API#57]
When i try to modify the greatswords (in Spartan Weaponry Ice and Fire), no matter what i do in the config file, it seems like the game just ignores it. I tried to increase the damage and attack speed, but even after i restarted the game, nothing changed. I tried it in multiple worlds and modpacks, non of the worked.

Minecraft version: 1.18.2
Forge version: 40.2.21

Also i would like to see config options for the longbows too, like it was in 1.12.2.
Edit: The config only changes the greatswords in the basic mod, but it doesn't in the addons like Spartan Weaponry Ice and Fire. Can you please make a config for those mods too?

**Comment by ObliviousSpartan** [comment]
This issue has to do with the fact that addon mods doesn't have access to the configs for this mod, so they don't know any values such as the weapons damage and attack speed have been changed.
The only way that I can get this working is to let addon mods have a callback when the base config is updated so they can update the values too.
I'll see what I can do about this

**Comment by Adam19lol** [comment]
Ok, thank you for the explanation! I hope you can do it. Good luck!
(Also, your mod is amazing, i really never make a modpack without it if it's avaiable for the version i playing with :D)
Have a nice day! :)

**Comment by rik30008** [comment]
ObviusSpartan, can you please explain me how can i let addon mods have a callback? I have the same issue as the guy before and is the first time i have this tipe of problem. Thank you for the reply
