### ISSUE TITLE
Crashed when I click Oil for recipe on JEI

### ISSUE THREAD

**Issue by PhilTheGreatLOL** [ObliviousSpartan/SpartanWeaponry-API#59]
When I need to see Oil damage boost for recipe, benefit or something but When I click to see then game crashed for mouseReleased event handler.
[crash-2024-07-17_23.59.46-client.txt](https://github.com/user-attachments/files/16277699/crash-2024-07-17_23.59.46-client.txt)

**Comment by ObliviousSpartan** [comment]
Hi there,
I've figured out that JEI had an update that added a new method that wasn't present in my Oil Recipes handler for JEI. That was causing the crash. The next update will have this fixed.

**Comment by PhilTheGreatLOL** [comment]
Oh good, Next update bug would(maybe) gone, I'd appreciate it!

**Comment by Shadowyjp** [comment]
Hi, this was already fixed? Im still crashing

**Comment by ObliviousSpartan** [comment]
The fix is now live. Closing issue
