### ISSUE TITLE
Items being created in the wrong namespace

### ISSUE THREAD

**Issue by XxInvictus** [ObliviousSpartan/SpartanWeaponry-API#6]
Trying to update Spartan Fire to 1.16.5 I have found multiple items being created in the spartanweaponry namespace instead of in the [modid] namespace, as shown below these include:
boomerang
tomahawk
heavy_crossbow
javelin
throwing_knife

> [31Jul2021 13:07:18.335] [Worker-Main-8/WARN] [net.minecraft.client.renderer.model.ModelBakery/]: Unable to load model: 'spartanweaponry:tomahawk_dragonbone#inventory' referenced from: spartanweaponry:tomahawk_dragonbone#inventory: java.io.FileNotFoundException: spartanweaponry:models/item/tomahawk_dragonbone.json
> [31Jul2021 13:07:18.335] [Worker-Main-8/WARN] [net.minecraft.client.renderer.model.ModelBakery/]: Unable to load model: 'spartanweaponry:throwing_knife_dragonbone#inventory' referenced from: spartanweaponry:throwing_knife_dragonbone#inventory: java.io.FileNotFoundException: spartanweaponry:models/item/throwing_knife_dragonbone.json
> [31Jul2021 13:07:18.335] [Worker-Main-8/WARN] [net.minecraft.client.renderer.model.ModelBakery/]: Unable to load model: 'spartanweaponry:heavy_crossbow_dragonbone#inventory' referenced from: spartanweaponry:heavy_crossbow_dragonbone#inventory: java.io.FileNotFoundException: spartanweaponry:models/item/heavy_crossbow_dragonbone.json
> [31Jul2021 13:07:18.335] [Worker-Main-8/WARN] [net.minecraft.client.renderer.model.ModelBakery/]: Unable to load model: 'spartanweaponry:javelin_dragonbone#inventory' referenced from: spartanweaponry:javelin_dragonbone#inventory: java.io.FileNotFoundException: spartanweaponry:models/item/javelin_dragonbone.json
> [31Jul2021 13:07:18.335] [Worker-Main-8/WARN] [net.minecraft.client.renderer.model.ModelBakery/]: Unable to load model: 'spartanweaponry:boomerang_dragonbone#inventory' referenced from: spartanweaponry:boomerang_dragonbone#inventory: java.io.FileNotFoundException: spartanweaponry:models/item/boomerang_dragonbone.json

**Comment by ObliviousSpartan** [comment]
Hi, sorry for the late reply.
This is an known issue as I found out working on some of my own addon mods as well. That will be fixed in the next major release.
It's also good to see that Spartan and Fire is still being worked on.

**Comment by XxInvictus** [comment]
Hey @ObliviousSpartan is there any chance of a "final" version of Spartan Weaponry being pushed upstream for 1.16.5 with the fixes or has work on 1.16.5 been halted for 1.17/8/9? SpartanFire has been on hold and I would love to get it across the line for 1.16.5 as a lot of legacy, fantastic mods came back out of the woodwork for this version.

**Comment by KreloX** [comment]
This issue no longer occurs on the 2.2.0 release candidate 2
