### ISSUE TITLE
Aluminium missing

### ISSUE THREAD

**Issue by KnifeWaifu** [ObliviousSpartan/SpartanWeaponry-API#61]
Good afternoon, I found a bug that even with aluminium as a material with the tag forge:ingots/aluminium it is not possible to create items from Spartan Weaponry consisting of aluminium, because SW itself does not see aluminium from GTCEU Modern. 
    Possible root of the problem:
   There are two ways to spell the word ‘aluminium’, these are: ‘alu**minum**’ and “alu**minium**”, both of them are correct, BUT the first one is an older variant and it comes from North America (USA) and Canada, and the second one is a more scientific name formed according to the rules of formation of names for chemical elements. In this case SW is trying to find aluminium ingots, and JUST DOES NOT SEE other aluminium ingots tagged with an extra ‘i’.

Solution path:
   We just need to add that the mod searches for aluminium ingots not only by the tag ‘forge:ingots/aluminum’ but also by ‘forge:ingots/aluminium’, this should increase compatibility with other mods, so it is likely that the same problem will be solved in the future in advance not only with Greg Tech Community Edition Modern, but also with other mods.

Other information:
Spartan Weaponry - 3.1.1
GTCEU - 1.3.1
Forge - 47.2.32
Minecraft - 1.20.1

![2024-07-22_19 40 37](https://github.com/user-attachments/assets/281a2769-1276-4058-9bb1-8e016f4bbe64)

**Comment by ObliviousSpartan** [comment]
Hi,
Yes you are absolutely right. The mod only looks under the tag "forge:ingots/aluminum" and not "forge:ingots/aluminium". So a solution to be able to look at both is required.
The solution I came up with is to create my own tag variant "spartanweaponry:ingots/aluminum" which contains both tags so it can look up both tags at the same time.
This will be added into the next update.

**Comment by ObliviousSpartan** [comment]
The fix for this is now live. Gregtech Aluminium should now be able to craft Aluminum weapons now.
Closing issue
