### ISSUE TITLE
Quiver crash [1.20.1 forge]

### ISSUE THREAD

**Issue by Cephelo** [ObliviousSpartan/SpartanWeaponry-API#64]
Occasionally when I pick up an item, I get this crash:
![image](https://github.com/user-attachments/assets/78da2c9c-1ed7-4806-bde6-82d435f7bc07)

Something weird is happening with Curio compat and quivers - note that I do not have a quiver equipped when this happens.

**Comment by ObliviousSpartan** [comment]
Hi,
Not exactly sure what is causing this, but I've added a sanity check to ensure that when looking for a valid quiver that it doesn't crash and fails gracefully and does nothing.
This fix will be in the next update

**Comment by ObliviousSpartan** [comment]
I've released what I hope is the fix for this problem. Closing issue.
If the problem still persists, feel free to re-open this issue
