### ISSUE TITLE
Are heavy crossbows and longbows supposed to be all equal?

### ISSUE THREAD

**Issue by alexvirgo13** [ObliviousSpartan/SpartanWeaponry-API#65]
I've noticed that all of the heavy crossbows and the longbows have the same stats (same damage, same charge up speed, same aiming speed and same range) no matter which material they're made of.
The only exception seems to be the lead and alumium versions which apply their respective material bonuses.
Edit: I forgot to mention it, but I noticed this on the 1.19 and 1.20 versions. I haven't tried any other version yet.

**Comment by ObliviousSpartan** [comment]
Hi,
If I recall correctly, I made a change in the 1.12.2 version (mod version 1.x) which added a few modifiers that adjusted the draw time and arrow velocity for Longbows and the load time, aim time and armor piercing modifier for Crossbows.
I've now just realized that I forgot to add this in the newer Minecraft versions 1.18.2-1.20.x (mod version 3.x).
I'm considering adding this back into the newer versions of this mod now that you've brought it up. Thanks!
