### ISSUE TITLE
Crash when querying brewing recipes using JEI, reported to be related to oil recipes.

### ISSUE THREAD

**Issue by KURUPA** [ObliviousSpartan/SpartanWeaponry-API#69]
Minecraft crash report provided indicates an issue with the Jei mod. Specifically, it seems there's a problem with the com.oblivioussp.spartanweaponry.compat.jei.JeiOilBrewingRecipe class. This class is likely responsible for integrating Spartan Weaponry's oil brewing recipes into the Jei recipe viewing functionality.

This is my crash report.

[crash-2024-08-03_18.11.47-client.txt](https://github.com/user-attachments/files/16479129/crash-2024-08-03_18.11.47-client.txt)

**Comment by ObliviousSpartan** [comment]
This issue was already reported here (issue #59)
I also released a fix very recently. Closing issue.
Also, nice.
