### ISSUE TITLE
DeferredRegister incompatibility

### ISSUE THREAD

**Issue by KreloX** [ObliviousSpartan/SpartanWeaponry-API#7]
When I use DeferredRegister to register spartan weapons then both .register and .createKatana methods set a registry name and that causes an exception.

public static final Item katanaFiery = SpartanWeaponryAPI.createKatana(FIERY, ItemGroup.TAB_COMBAT);
    
public static final RegistryObject<Item> KATANA_FIERY = ITEMS.register("katana_fiery", () -> katanaFiery);

**Comment by ObliviousSpartan** [comment]
Yeah, sorry. This was made before DeferredRegister was even a thing. 
I plan on adding a boolean flag to the API methods to create the weapons that prevents automatically setting the registry name to prevent this from happening. This should hopefully make it more compatible with DeferredRegister

**Comment by ObliviousSpartan** [comment]
I've just released a mod and API update which adds compatibility for DeferredRegister. Atm it has a bug which causes a crash (see issue #9). Once that is fixed, it should be safe to use

**Comment by KreloX** [comment]
It works since the update, no need for this being open.
