### ISSUE TITLE
Aternos Spartan weaponry error

### ISSUE THREAD

**Issue by Darkgonauta** [ObliviousSpartan/SpartanWeaponry-API#70]
error minecraft internal exception: io.netty.handler.codec.decoderexception: java.lang.nosuchmethoderror: "float com.obliviussp.spartan.weaponry.item.crafting.itagcookingrecipe.m_43750_()"

**Comment by Darkgonauta** [comment]
version del juego: 1.20.1
version del mod: 3.1.2

**Comment by equinoxvee** [comment]
Downgrade the version, the one that worked for me is 3.1.1.

**Comment by ObliviousSpartan** [comment]
That would work for now. But I've been looking at it from my end and I've been able to replicate the issue and fix it.
I'll roll out an update for it shortly.

**Comment by ObliviousSpartan** [comment]
The update is now live. Closing issue
