### ISSUE TITLE
Possible crash on servers, probably due to quivers

### ISSUE THREAD

**Issue by ghost** [ObliviousSpartan/SpartanWeaponry-API#74]
I've been running a Forge 1.20.1 server, and one of the server members has experienced numerous crashes in the past day or so. I managed to fix it once by removing his player data, but it seems he has started crashing again. The first set of crashes seems to have only affected that player, but the most recent crash seems to have caused the entire server to crash.
Log for first crash: https://mclo.gs/KMqLnX6
Crash report for most recent crash: https://mclo.gs/67KR3Oa

The reason why I am bringing this up on the issues page for Spartan Weaponry is that, in both of these logs/crash reports, Spartan Weaponry was listed many times, probably more than any other mod. In particularly, it seems that quivers were mentioned a lot, so I suspect the issue may be due to quivers.

These issues have occurred on version 3.1.3 of the mod.

**Comment by ObliviousSpartan** [comment]
I've been looking at the crash reports and I can't seem to reproduce this.
Do you know what the server member did for this crash to happen?

**Comment by ghost** [comment]
I don't remember what the server member did. I don't know what else to do to reproduce the crash, so I'll just close this issue.
