### ISSUE TITLE
Extra mob heads crash

### ISSUE THREAD

**Issue by Woolamb** [ObliviousSpartan/SpartanWeaponry-API#81]
I've had this issue. Either in my inventory, extra item menus or just floating custom heads crash my game. Minecraft will close, open the launcher and show an error maessege that basically says it cannot render/load the skull model, and it has also caused me to get blue screens some times. I really like this mod and its weapons, but it getting more frustrating then enjoyable. Some insight would be nice :)

**Comment by ObliviousSpartan** [comment]
I need some more information before I get to the bottom of this...
- Which version of the mod are you using?
- What are the exact steps you are using to cause this to happen? 
- Which head(s) are you trying to view/use? 
- Also what do you mean by floating heads?

Also, can you please provide a crash report that is generated when this crash happens?
I will say though, that I'm skeptical that this mod is causing a blue screen though... could it be a problem with running out of memory/storage?

**Comment by PixLNickz** [comment]
i have the same thing he's having, not blue screens, just crashes
[crash-2024-12-29_23.20.05-client.txt](https://github.com/user-attachments/files/18271086/crash-2024-12-29_23.20.05-client.txt)
