### ISSUE TITLE
[SUGGESTION] Some config options and compatibilty suggestions for consistency and modpack devs

### ISSUE THREAD

**Issue by TyrionReyukra** [ObliviousSpartan/SpartanWeaponry-API#84]
Hello, I've been working on a 1.20.1 modpack for some friends and I'm a huge advocate for configurability and customization.

I love this mod, especially when paired with Better Combat, as this has the most cross-mod compatibility I've seen out of all of the currently available weapon mod options (Aether, Ice & Fire, Twilight Forest, etc.)

For my modpack I've removed all weapon effects (things like Reach, Enhanced Knockback, etc.) using datapack tags (Thank your letting that be customizable through the datapack system btw), as I believe that with Better Combat the different attack animations, attack ranges, speeds and combos are enough.
However, when removing all effects from a weapon, there is still empty space on the item tooltip reserved for information that is no longer there. This also expands to two empty lines with holding shift.

My suggestion for this is to either remove the reserved tooltip space unless there are applied effects, or have a config option to disable the additional tooltip information (or specific parts if possible, such as keeping throwing weapon ammo count, but removing the charge time).
I would also like this to apply to Longbows and Heavy Crossbows, as some might not wish to have different draw times and projectile speeds, or not have them show and let the player figure out which material does what.
I know this isn't the Spartan Shields page, but I would also like the see this applied the the "Max Protection" tooltip on those, as it's just the items durability, and having other mods that show item durability leads to a very bloated and messy tooltip.

Speaking of bows, I would also like to see more compatibility with the ammo types the Heavy Crossbows can shoot.
I've tried adding vanilla Firework Rockets and the Glow Flare from Galosphere to the "spartanweaponty:bolts" tag for parity with the vanilla crossbow, but ran into some issues. Heavy Crossbows can load the items as ammunition, but not fire them.

The last suggestion I have is about the Simple Handle/Pole items. I've used Item Obilterator to remove the items from general gameplay.
However, right clicking a stick on grass still destroys the grass and consumes the stick, but drops no item (as intended with Item Obliterator).
This also has an issue with Supplementaries, which allows you to place sticks as a building block. Trying to place the stick as a block on grass will provide the same effect. Breaking the grass, consuming the stick and not dropping an item (as intended with Item Obliterator), but not placing the stick as a block.
I would like to see a possible config toggle for creating the Simple Handle/Pole items via grass interaction, or configurability through the datapack system.

I apologize for the lengthy suggestion post, I'm a stickler for consistency and while none of these are game-breaking, I believe the more customizeable a mod is for the user, whether cosmetic or gameplay effecting, the better.

Thank you for the amazing weapon mod, supporting it through the years, and thank you for your time :)

**Comment by IdrisQe** [comment]
Hi, not sure why this has been marked as completed?
I'd like this re-opened if possible, as it would be really nice to have more ability to customize tooltips in general.
Spartan weapons stick out really badly against most other weapons as they're the only one with traits showing as they do.
It would be nice to be able to modify how the trait tooltips show, or disable them entirely (even if the weapons still have traits) in order to have some consistency in tooltips. It would also be nice to be able to disable or alter the keybind used to show detailed trait information, as on some weapons, with other mods especially, this can cause extend off-screen.
