### ISSUE TITLE
Crafting a diamond (or potentially any upgraded) quiver via smithing table and holding a bow causes the game to crash

### ISSUE THREAD

**Issue by dankxen0n** [ObliviousSpartan/SpartanWeaponry-API#87]
[crash-2024-10-06_18.38.44-server.txt](https://github.com/user-attachments/files/17271246/crash-2024-10-06_18.38.44-server.txt)
[latest.log](https://github.com/user-attachments/files/17271247/latest.log)

Title and above logs are the only information i have about this.

**Comment by dankxen0n** [comment]
Update: attempting to edit all problematic items out of inventory via NBTexplorer has not changed a single thing. The game still behaves as if i still have the quiver, arrows, and bow in my inventory. This needs to be fixed via an update.

**Comment by Kettle5000** [comment]
got the same issue, this should not be ignored as is not fixed yet.
