### ISSUE TITLE
Error with the boomerang (DefferedRegister)

### ISSUE THREAD

**Issue by Samlegamer** [ObliviousSpartan/SpartanWeaponry-API#9]
Hello I tried to update my mod with the latest version of the api.
After launching the game an error occurred which would have to do with the BoomerangItem.
Is there anything to do with the new version of the api?

[crash-2022-03-31_00.01.13-fml.txt](https://github.com/ObliviousSpartan/SpartanWeaponry-API/files/8384455/crash-2022-03-31_00.01.13-fml.txt)

**Comment by ObliviousSpartan** [comment]
Hi. Well that was quick.
It's more to do with a debug logging option that caused this crash because it expects the item to have a registry name before the model overrides are registered. Oops. 
I'm gonna release an update to the mod that should fix this issue. I'll let you know when it's out.

**Comment by Samlegamer** [comment]
Good evening, just to let you know that I have just tested the rc-2 version released today and everything works fine, no crashes etc...

**Comment by ObliviousSpartan** [comment]
Sweet; sorry it took so long to fix.
Closing the issue
